schema_version = "1.0.0"

id = "import_minecraft_replay"
version = "0.8.0"
name = "Import Minecraft Replay"
tagline = "The Blender component of Igrium's Replay Exporter"
maintainer = "Igrium"
type = "add-on"

# Blender version
blender_version_min = "4.2.0"

# License
license = ["SPDX:GPL-3.0-or-later"]

[permissions]
files = "Import/export replay files"

